### ISSUE TITLE
What if the route action needs to set a controller property?

### ISSUE THREAD

**Issue by krzkrzkrz** [dockyard/ember-route-action-helper#10]
What would you do when the closure action needs to set a controller property?

Template has:
```
{{#if showOtherForm}}
  ...
{{/if}}

{{some-component save=(route-action "saveUser")}}
```

Route has:
```
  actions: {
    saveUser() {
      let user = this.get('model');

      user.save().then(() => {
        this.set('showOtherForm', false); // Will fail, since route does not share controller properties
        return true; // Return true so some-component can do something else
      });
    },
```

Unfortunately, routes don't share controller properties (at least, not until routable components land).

In situations like this, should we just use a "normal" closure action (in the controller instead). i.e. `{{some-component save=(action "saveUser")}}`? But then, you wont have the `return` feature.

Or, is it still possible to still use the plugin somehow?

**Comment by danmcclain** [comment]
@krzkrzkrz You can access the controller from the route as `this.controller`

**Comment by krzkrzkrz** [comment]
Oh nice. That works. So I guess the properties still need to be defined in the controller
