### ISSUE TITLE
Support for action bubbling by 'return true' in a route action.

### ISSUE THREAD

**Issue by CodeOfficer** [DockYard/ember-route-action-helper#17]
I saw part of a discussion about this in https://github.com/DockYard/ember-route-action-helper/pull/4  ... I'm wondering if there is a specific reason for not supporting bubbling ... Note: I did see the fine print in the READ ME after the fact ... of course that's how I roll though.

A client's app I am working on uses child route actions to handle analytics tracking, and then they bubble to the the application route for click handling (transitionTo etc)... seems a valid use case.

**Comment by danmcclain** [comment]
With closure actions you get access to return values, so it's hard to say when you have an action, say, to check if a person has logged in successfully, whether you want that value to say "this should bubble" or that "this action did something successfully"

**Comment by CodeOfficer** [comment]
Isn't returning true specifically a special case?

**Comment by danmcclain** [comment]
It's not a special case in closure actions

@rwjblue/@poteto can you confirm?

**Comment by rwjblue** [comment]
Closure actions don't bubble at all, since this addon is emulating that behavior we do not bubble.

**Comment by CodeOfficer** [comment]
Thanks!
