### ISSUE TITLE
Gracefully handling `undefined` route actions in tests

### ISSUE THREAD

**Issue by batjaa** [DockYard/ember-route-action-helper#19]
Any thoughts on how to gracefully handle `undefined` actions in tests?  `sendAction` doesn't fire/call the event when the action is `undefined`, quite useful when writing tests. Because you won't need to define every action or pass a `noop`.

**Comment by martndemus** [comment]
This is how the new style actions work. If you want to work around that you could either:

- Decouple the action in your component's template by calling an action on your component and then have that call the action passed in.
- Use the optional helper from ember-composable-helpers: https://github.com/DockYard/ember-composable-helpers#optional
