### ISSUE TITLE
Check current controller before traversing routes?

### ISSUE THREAD

**Issue by bttf** [DockYard/ember-route-action-helper#20]
Currently `route-action` will not find an action on the local controller. If an action is called and it is not defined on any parent routes, but is defined on the controller, `route-action` will fail with 'Unable to find action'.

Might there be a case when we will need `route-action` to be able to use actions from the local controller as well as parent routes? (E.g. a template that is used across different route/controller contexts)

**Comment by poteto** [comment]
Please use a regular `action` if you want to target the controller. With `route-action` we favor explicitness, only actions on routes will be hit.
