### ISSUE TITLE
Fail immediately instead of when the action is invoked?

### ISSUE THREAD

**Issue by nucleartide** [DockYard/ember-route-action-helper#21]
Hey all,

First of all, great work with the library! 👍  So I noticed that `route-action` doesn't immediately report whether the route action exists, while `action` does. For example:

```hbs
{{!--
  upon visiting route, will fail with "Uncaught Error: An action
  named 'doesNotExist' was not found in (generated login controller)."
--}}
{{login-panel authorize=(action 'doesNotExist')}}

{{!-- upon visiting route, will not fail immediately until "authorize" action is called --}}
{{login-panel authorize=(route-action 'doesNotExist')}}
```

It seems like you would get the desired immediate error if [lines 44 to 45][1] are moved out of that function expression.

I feel like it doesn't really matter with good tests, but what do you think?

[1]: https://github.com/DockYard/ember-route-action-helper/blob/master/addon/helpers/route-action.js#L44

**Comment by poteto** [comment]
I like that idea, failing immediately would likely be a better experience. Would you like to open a PR for it?

**Comment by nucleartide** [comment]
Yep, maybe later today or tomorrow
