### ISSUE TITLE
Integration test for component using route-action helper

### ISSUE THREAD

**Issue by Leooo** [DockYard/ember-route-action-helper#24]
Hello, would you have any example of integration testing for a component using `route-action`?

=> Can not use an external action as for a normal action:

`````
  // not working
  this.set('externalAction', (actual) => {
    let expected = { comment: 'You are not a wizard!' };
    assert.deepEqual(actual, expected, 'submitted value is passed to external action');
  });

  this.render(hbs`{{appointment.contact-number-form bookAppointment=(action externalAction)}}`);

  let $btn = this.$('button:contains("Confirm and book")');
  $btn.click();
`````

Thanks

**Comment by tragiclifestories** [comment]
I don't think this would be possible: in an integration test, you do not have access to an application instance, and therefore there is no router, and therefore there is no route. Looking at the implementation, it would be devilishly difficult to stub everything out (and the result would be very, very brittle). Use an acceptance test.

**Comment by Leooo** [comment]
Yes I used a component without a route-action, and the action passed to it using a route-action, that makes testing easier. Thanks.

**Comment by ghost** [comment]
@Leooo  - have a look at this https://github.com/DockYard/ember-route-action-helper/commit/58ac3f73dec81c314ebba183f5f943cc2473a0d5
