### ISSUE TITLE
closure-action path changed in master

### ISSUE THREAD

**Issue by rlivsey** [DockYard/ember-route-action-helper#25]
Just a heads up, it looks like the [path](https://github.com/DockYard/ember-route-action-helper/blob/c80ba222025f99f885c376afc107f979505e9e92/addon/-private/internals.js#L3) to the closure-action has [changed in Ember master](https://github.com/emberjs/ember.js/commit/0cd80863fea4bc76b3cdb1296c718a1e2a63aa28)

It's now at `ember-htmlbars/keywords/closure-action` instead of `ember-routing-htmlbars/keywords/closure-action`

Not sure if there's a nice way of checking the path exists, or falling back if it fails?

**Comment by rwjblue** [comment]
Thank you! We'll need to check at least the old and new paths (and likely a third for glimmer version).
