### ISSUE TITLE
Glimmer 2 Support

### ISSUE THREAD

**Issue by GavinJoyce** [DockYard/ember-route-action-helper#29]
I've been trying an early Glimmer 2 alpha with our Intercom app and I've been documenting issues that I've come across in this repo: https://github.com/GavinJoyce/glammer/issues

Here's an issue and reproduction for `ember-route-action-helper`: https://github.com/GavinJoyce/glammer/issues/2

`ember-route-action-helper` doesn't yet work with Glimmer 2 as `ember-routing-htmlbars/keywords/closure-action` isn't available. I haven't yet looked any further into this

**Comment by GavinJoyce** [comment]
This seems to be fixed on master. It can be closed once the next release is available

**Comment by poteto** [comment]
Thanks, sorry for forgetting!

**Comment by poteto** [comment]
Released in `1.0.0`
