### ISSUE TITLE
Helpers may not be used in the element form

### ISSUE THREAD

**Issue by fknoll** [DockYard/ember-route-action-helper#31]
I replaced this:
```<button {{action "toDay"}}> Today </button>```

… with this:
```<button {{route-action "toDay"}}> Today </button>```

... and got this error:
```ember.debug.js:19695 Uncaught Error: Assertion Failed: Helpers may not be used in the element form, for example <div {{my-helper}}>.```

**Comment by martndemus** [comment]
@fknoll The correct form is

`<button {{action (route-action "toDay")}}> Today </button>`

**Comment by fknoll** [comment]
@martndemus  Thanks! I just reviewed documentation, and realize I must have missed the text about the correct form. I apologize.
