### ISSUE TITLE
Need to do this.myFunction.call(this) in route's action, for certain functions within the route.

### ISSUE THREAD

**Issue by somechild** [DockYard/ember-route-action-helper#34]
So currently, my route looks something like this:

```
myFunction(arguments...) {
 let myVariable = this.get('something');
 // do something
},

actions: {
 myAction() {
 ...
 this.get('myFunction')(...params);
 ...
 }
}
```

executing `route-action "myAction"` will result in an error where it says cannot read property `get` of `undefined` on `let myVariable = this.get('something')`.

I currently fix this by doing `this.get('myFunction').call(this, ...params)` within the action.

I'm not sure how specifically the helper works, but is there any way to not have to do `this.get('myFunction').call(this..`?

Update:
Doing `this.myFunction.(...params)` resolves the error without having to use `call`

**Comment by rwjblue** [comment]
In general, we do bind the action to the route that it is found on ([see here](https://github.com/DockYard/ember-route-action-helper/blob/master/addon/helpers/route-action.js#L47)). Can you provide a reproduction that shows the issue?

**Comment by somechild** [comment]
Oh okay so what I've discovered is that in my example above, it was failing when I did `this.get('myFunction')(...params)`
However, doing `this.myFunction(...params)` does not throw the `cannot read property get of undefined` on `let myVariable = this.get('something')`

So this would be a workaround to `.call`

Reproduced: http://jsbin.com/miqaperoro/1/edit?html,js,output
