### ISSUE TITLE
Integration tests support in 2.0.0

### ISSUE THREAD

**Issue by ilucin** [DockYard/ember-route-action-helper#39]
Since #37 was merged we basically can't have integration tests for components using route-action helper. It breaks on getting current route handler (router.router.currentHandlerInfos).

I guess there has to be an API for integration testing? Or am I missing something here? :)

**Comment by martndemus** [comment]
You should only use `{{route-action}}` in a route's template. Not in the templates of components.

**Comment by ilucin** [comment]
Aha, you're right, I was hacking it a bit here. Back to refactoring I guess, sorry for interruption :)

**Comment by amk221** [comment]
Doh! This will be frustrating
```handlebars
{{! my-route/template.hbs }}
{{my-route/-components/my-route-component}}
```

**Comment by ilucin** [comment]
@amk221 I feel you. I'm kinda doing the same thing :)

**Comment by amk221** [comment]
Essentially, components specific to the route. Almost like partials but not really

**Comment by blimmer** [comment]
@martndemus why impose that it must be used in the route template? One of the best parts of this addon is to prevent having to bubble in deeply nested components.

This change in 2.0 requires bubbling up to the top-most component, which will reintroduce a ton of boilerplate bubbling for me.

**Comment by rwwagner90** [comment]
@blimmer I agree. I don't see why we can't support it

**Comment by martndemus** [comment]
Using it in anything other than a route template is a hack. This should not be used as an escape hatch out of bubbling actions. This addon was born as a sort of a temp hack pending routable components supporting normal closure actions.

**Comment by rwwagner90** [comment]
@martndemus I thought the whole point was to bubble up the the current route, then application route, etc, regardless of what template or component you were in?

**Comment by martndemus** [comment]
> I thought the whole point was to bubble up the the current route, then application route
Yes, but it doesn't bubble, it just goes up the route hierarchy to find the first action matching given name.

> regardless of what template or component you were in?
No.

**Comment by rwwagner90** [comment]
@martndemus it's very useful to be able to call anywhere without passing all the way down, but I will try to refactor to not do that.

**Comment by blimmer** [comment]
I agree with @rwwagner90 and this is the only reason I use this addon. 

Imagine having an action in your application route that you want to call from a deeply nested component. I hated having to bubble those all the way up to simply escape to the nested components.
