### ISSUE TITLE
Another Glimmer 2 issue?

### ISSUE THREAD

**Issue by jamesdixon** [DockYard/ember-route-action-helper#40]
Hi,

I'm seeing the same exact error as in #29. I ran into this with Ember 2.9-beta.1 and was able to resolve it by installing v1.0.0 of this library. However, I've now upgraded to beta.2 and am seeing the same issue. Note that I also upgraded this library to 2.0.0.

Anyone else seeing this?

cc: @gavinjoyce

**Comment by rwjblue** [comment]
Can you please provide a demo repo, and the actual error you receive?

**Comment by jamesdixon** [comment]
@rwjblue admittedly, I was not able to reproduce in a fresh repo. I'll close for now and see if I can't track down where the issue lies.

The exact error is: `Uncaught Error: Could not find module ember-routing-htmlbars/keywords/closure-action`.

There's actually a good chance that it has nothing to do with this addon after all. I noticed that when I click on anything that changes a route (link-to, route-action, etc), the whole page reloads.

FWIW, I'm running 2.9.0-beta.2-beta+a7c49bf5.

Does it make sense to open an issue in the Ember repo?

**Comment by rwjblue** [comment]
Likely something is using that module (which doesn't exist in 2.9), you need to grep your `node_modules` for it to find out which addon is the culprit and report to their issue tracker (after checking that there isn't an already released update that resolves).

Here is a snippet from https://github.com/emberjs/ember.js/issues/14239#issuecomment-245792725 that should help:

```
grep --recursive "ember-routing-htmlbars/keywords/closure-action" node_modules/
```

**Comment by jamesdixon** [comment]
@rwjblue ha, yeah, I was actually in the midst of doing that 👍 That was advice you provided to me previously.

I'm just getting some strange output when running that command so trying to figure out what's going on.

**Comment by jamesdixon** [comment]
Seeing it in `ember-composable-helpers`, `ember-route-action-helper` and `ember-simple-auth`. Specifically, within Ember Simple Auth, it's under the `fastboot-dist/` directory. Note that I'm not using Fastboot.

**Comment by rwjblue** [comment]
ember-composable-helpers just released a version compatible with 2.9+.

**Comment by rwjblue** [comment]
ember-route-action-helper is also passing all of its tests against beta, canary, and alpha.

**Comment by jamesdixon** [comment]
ember-composable-helpers update resolved the issue.

thanks for your help, @rwjblue!
