### ISSUE TITLE
Testing route-action used in a component

### ISSUE THREAD

**Issue by milindalvares** [DockYard/ember-route-action-helper#42]
I have some `route-action`s set up for saving models and such within a component. Testing that component produces this error:

    TypeError: Cannot read property 'currentHandlerInfos' of undefined

I'm unsure how to proceed here, any help?

**Comment by martndemus** [comment]
In which template did you use the helper?

**Comment by poteto** [comment]
The helper should not be used in the component's template, pass the action in.

**Comment by milindalvares** [comment]
So it's not a recommended practice to use eg `<button {{action (route-action 'edit' model) }}>Edit</button>` inside `/components/edit-product.hbs`? It's so convenient that I'm wondering what the pitfalls of doing so are…?

**Comment by artzte** [comment]
Example of test workaround here. https://github.com/DockYard/ember-route-action-helper/pull/43/commits/58ac3f73dec81c314ebba183f5f943cc2473a0d5
