### ISSUE TITLE
Fix getowner deprecation

### ISSUE THREAD

**Issue by Frozenfire92** [DockYard/ember-route-action-helper#45]
With a new release of ember (I'm thinking 2.10) this deprecation warning is happening everywhere

```
ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill
```

Pull request incoming!

**Comment by Prabhakar-Poudel** [comment]
looks like this issue persists in 2.0.1 release.

I'm still getting the warning.

And your master branch does include a refrence to ember-getowner-polyfill in package.json

Please fix it quickly.
