### ISSUE TITLE
get-owner-polyfill

### ISSUE THREAD

**Issue by rstudner** [DockYard/ember-route-action-helper#48]
Not a biggie to fork it/remove it etc.  

Wondered if there was a timeline on if/when this plugin would remove it and be "Ember > 2.3" (to remove the need to suppresses the deprecation warnings lah lah.

just curious!

**Comment by pcambra** [comment]
I think this has been removed in https://github.com/DockYard/ember-route-action-helper/issues/45, hasn't it?
