### ISSUE TITLE
How can I send a route-action from component instead of template

### ISSUE THREAD

**Issue by masciugo** [DockYard/ember-route-action-helper#51]
In few words I would like to invoke the action from my component.js instead of helper usage. Is it possible?

**Comment by urbany** [comment]
You can pass the action to your component like this:
`{{my-component myAction=(route-action 'action-name')}}`

and inside your `my-component.js` do this `this.get('myAction')()`

**Comment by poteto** [comment]
What @urbany said

**Comment by jordpo** [comment]
We noticed using the latest version that you can use the `route-action` helper directly in the component template and it will look for the action on the current active route then bubble (so you don't have to even set it as a property on the component context). It feels funny though, like it breaks the explicit connection of DDAU. Should this be documented in any way or is there a way to have the library enforce that you are calling the helper in a controller context?

**Comment by darrenkovalchik** [comment]
I've noticed this as well. I was definitely under the impression that `route-action` was only accessible on route templates.

**Comment by kovalchik** [comment]
I've noticed this as well. I was definitely under the impression that `route-action` was only accessible on route templates.

**Comment by urbany** [comment]
That's funny, I think I always used it inside components.

**Comment by jordpo** [comment]
@urbany should I open a new issue to at the very least get this behavior documented?

**Comment by poteto** [comment]
This is unintended behavior. It does work, but it's not supported and shouldn't be relied on
