### ISSUE TITLE
Fails to find "native" - not transpiled - async action

### ISSUE THREAD

**Issue by RobIsHere** [DockYard/ember-route-action-helper#55]
The check at https://github.com/DockYard/ember-route-action-helper/blob/master/addon/helpers/route-action.js#L28 fails for async function. Because Ember.typeOf returns "object".

"async function" checks are not documented in Ember.typeOf. So I don't know if this should not be used or if it's a thing that should work in Ember.typeOf.

https://github.com/emberjs/ember.js/issues/15151

**Comment by rwjblue** [comment]
We should just use the native `typeof` there...
