### ISSUE TITLE
Plugin not working with nested components

### ISSUE THREAD

**Issue by krzkrzkrz** [dockyard/ember-route-action-helper#6]
I've got the following:
```
{{confirmation-button confirmAction=(action "settle")}}
{{confirmation-button confirmAction=(route-action "settle")}}
```
In the `confirmation-button` template. I've got another component:
```
{{loading-button clicked=attrs.confirmAction}}
```
The loading button component object has:
```
  click() {
    console.log(this.attrs.clicked);
    this.attrs.clicked();
  }
```
When the the `loading-button` component is clicked. There are no issues with `{{confirmation-button confirmAction=(action "settle")}}`

`console.log`  returns:
```
function () {
        var args = arguments;
        if (valuePath && args.length > 0) {
          args = Array.prototype.slice.apply(args);
          args[0] = _emberMetalProperty_get.get(args[0], val…
```

However, `{{confirmation-button confirmAction=(route-action "settle")}}` returns:
`Uncaught TypeError: this.attrs.clicked is not a function`

`console.log`  returns:
```
Object {MUTABLE_CELL [id=__ember14546043676981018055021323]: true}MUTABLE_CELL [id=__ember14546043676981018055021323]: trueupdate: (val)value: ()__proto__: Object
```

Is it because `ember-route-action-helper` is returning a different `attr` object?

**Comment by poteto** [comment]
I'm updating the readme, but you should do:

```hbs
{{confirmation-button confirmAction=(action (route-action "settle"))}}
```

This is primarily because the `route-action` helper doesn't return a closure action, so you have to wrap it in an `action` subexpression to turn it into one.

As a sidenote, you don't have to use `attrs` in your template, you can do:

```hbs
{{loading-button clicked=confirmAction}}
```

**Comment by krzkrzkrz** [comment]
Thanks for that! Seems to work.

Awesome plugin. Keep up the good work!

Closing case for now.

**Comment by brancusi** [comment]
Same issue solved! Thanks for the nice addon. Any way to make this a closure action by default? Seems like most of the actions end up being consumed deeper down.

**Comment by krzkrzkrz** [comment]
@brancusi Maybe open up another issue? I agree with closure action by default. Makes more sense

**Comment by rwjblue** [comment]
I think we can fix this.

**Comment by rwjblue** [comment]
Submitted a PR to help prevent folks from double wrapping.

**Comment by krzkrzkrz** [comment]
Sweet! Looking forward to this
