### ISSUE TITLE
Cannot read property 'currentHandlerInfos' of undefined

### ISSUE THREAD

**Issue by erichonkanen** [DockYard/ember-route-action-helper#79]
My integration test that contains some buttons with `route-action` set is throwing the error:

`Cannot read property 'currentHandlerInfos' of undefined`

How can I get around this for an integration test? The route-action's that are called are set on the app route whereas I'm just testing a component here...

Thanks

**Comment by Sola-BG** [comment]
I believe it is not best practice to use a helper in a component.  Read more here https://github.com/DockYard/ember-route-action-helper/issues/42

**Comment by Sola-BG** [comment]
Someone has been kind enough to post a work-around here https://github.com/DockYard/ember-route-action-helper/commit/58ac3f73dec81c314ebba183f5f943cc2473a0d5
