### ISSUE TITLE
[dependencies] remove ember-getowner-polyfill

### ISSUE THREAD

**Issue by gabrielcsapo** [DockYard/ember-route-action-helper#85]
Getting this everywhere 

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: *addon* -> ember-route-action-helper -> ember-getowner-polyfill -> ember-cli-babel
```

Can we remove ember-getowner-polyfill?

**Comment by rwjblue** [comment]
Just needs to update to the latest version of it, which avoids the deprecation.

**Comment by rwjblue** [comment]
Actually the latest version of this addon already includes the latest version of ember-getowner-polyfill, please update which version you are using...

**Comment by gabrielcsapo** [comment]
We were using 1.1.0 thank you! Upgrading and don't see the issue anymore.
