### ISSUE TITLE
Use of _routerMicrolib.currentHandlerInfos private API is deprecated

### ISSUE THREAD

**Issue by jacobq** [DockYard/ember-route-action-helper#86]
See https://emberjs.com/deprecations/v3.x/#toc_remove-handler-infos

https://github.com/DockYard/ember-route-action-helper/blob/dc9ca2e0276f887b55639f6fb858c00bcbe53d76/addon/helpers/route-action.js#L10-L12

**Comment by jordpo** [comment]
I'm not sure how this library can get around the deprecation without an update in the RFC. I don't see anything planned for exposing route handler infos. 

I ending up rolling my own helper
https://gist.github.com/jordpo/9195150854f276f0e9ceb1200d123611

**Comment by jacobq** [comment]
@jordpo Pardon my ignorance, but could you explain the difference between the private `HandlerInfo` and the public [`RouteInfo`](https://emberjs.com/api/ember/3.7/classes/RouteInfo). 

[RFC0095 says](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md#deprecating-willtransition-and-didtransition):

> Everything you can do with handlerInfos can be done with the RouteInfo type that is proposed in this RFC, with the benefit of sticking to supported public API.

So were they not considering this use case when they said "everything" then?

**Comment by Frozenfire92** [comment]
:+1: on getting this fixed, just updated to ember 3.7.x and getting this deprecation

**Comment by Frozenfire92** [comment]
I suspect #87 fixes thsi

**Comment by BnitoBzh** [comment]
I made a new PR #88 with passed tests.
I am waiting merge ..

**Comment by jrcooke2** [comment]
Can confirm #88 works as expected

**Comment by btecu** [comment]
I suggest you stop waiting and instead use a local helper.

**Comment by poteto** [comment]
Closed by #88
