### ISSUE TITLE
Does not work with `action` decorator

### ISSUE THREAD

**Issue by Turbo87** [DockYard/ember-route-action-helper#90]
We've tried to move from the `actions` hash to use `action` decorators instead (on a classic `.extend()` class), but it seems that the `route-action` helper is not able to find the action now:

> Assertion Failed: [ember-route-action-helper] Unable to find action

Any thoughts on this? Should this be supported?

/cc @martndemus @cibernox

**Comment by BnitoBzh** [comment]
it works for us, we use `@action` decorators and the `route-action` helper.
Have you an example on how you use the `route-action` helper in your templates ?

**Comment by Turbo87** [comment]
Interesting! Then it might be an issue on our side. Let me dive in deeper then :)
