### ISSUE TITLE
v2.0.7 contains `.node_modules.ember-try` folder

### ISSUE THREAD

**Issue by Turbo87** [DockYard/ember-route-action-helper#98]
see https://unpkg.com/browse/ember-route-action-helper@2.0.7/

**Comment by ondrejsevcik** [comment]
this was fixed in #89 but there was no release yet with this fix.

I would also appreciate 🙏 a new release with this fix. It slows down our CI build.

**Comment by poteto** [comment]
Released in `2.0.8`, sorry about that!

**Comment by Turbo87** [comment]
Thanks Lauren! :)
